---
title: "Linear Models"
author: "Ruilian Zhang"
date: "11/16/2021"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


Load NYC airbnb data.

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group
  ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighbourhood, room_type)
```

Visulizations...

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) +
  geom_point()
```


Let's fit a linear model...

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

Let's look at this...

```{r}
summary(fit)
summary(fit)$coef

fit %>% broom::tidy()
```

If you want to present output...

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "borough", "Bourough: ")) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
```


## Diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point()

modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = resid)) +
  geom_density() +
  xlim(-200, 200)
```


## Interactions? Nesting?

Let's try a different model...

```{r}
fit = lm(price ~ stars  * borough + room_type * borough, data = nyc_airbnb)

broom::tidy(fit)
```

Let's try nesting...

```{r}
nyc_airbnb %>% 
  relocate(borough) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~ lm(price ~ stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)
  ) %>% 
  select(borough, lm_results) %>% 
  unnest(lm_results) %>% 
  filter(term == "stars")
```

Look at neighbourhoods in Manhattan...

```{r}
manhattan_le_results_df = 
  nyc_airbnb %>% 
    filter(borough == "Manhattan") %>% 
    select(-borough) %>% 
    relocate(neighbourhood) %>% 
    nest(data = price:room_type) %>% 
    mutate(
      lm_fits = map(.x = data, ~ lm(price ~ stars + room_type, data = .x)),
      lm_results = map(lm_fits, broom::tidy)
    ) %>% 
    select(neighbourhood, lm_results) %>% 
    unnest(lm_results)

manhattan_le_results_df %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate)) +
  geom_density()

manhattan_le_results_df %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighbourhood, y = estimate)) +
  geom_point() +
  facet_grid( ~ term)
  
```

